export const SUBMISSION_CLASSIFICATION_SUPPLIER_REGISTRATION="9978";
export const SUBMISSION_CLASSIFICATION_PROFILE_UPDATES="9979";
export const SUBMISSION_CLASSIFICATION_ADD_REMOVE_SCOPE="9980";
export const SUPPLIER_FINANCE_PROJECT_TYPE_PREVIOUS="9681";
export const SUPPLIER_FINANCE_PROJECT_TYPE_ONGOING="9682";
export const SUPPLIER_FINANCE_TOTAL_ASSETS="9691";
export const SUPPLIER_FINANCE_TOTAL_LIABILITIES="9692";
export const PRE_QUALIFICATION_STATUS_QUALIFIED ="7011";
export const PRE_QUALIFICATION_STATUS_REJECTED ="7012";
export const PRE_QUALIFICATION_STATUS_NEEDMOREINFO ="7013";

export const PRE_QUALIFICATION_SCORE_STATUS_QUALIFIED ="7001";
export const PRE_QUALIFICATION_SCORE_STATUS_REJECTED ="7002";
export const PRE_QUALIFICATION_SCORE_STATUS_NEEDMOREINFO ="7003";

export const  CATEGORY_SCOPE_ATTACHMENT_TYPE_SUCCESS_STORIES="9968";
export const CATEGORY_SCOPE_ATTACHMENT_TYPE_SPECIALIZED_PROFILES ="9969";

export const fileUpload = "uploadAttachment"
export const fileDownload = "downloadAttachment"
export const fileIsExist = "isAttachmentExist"
export const attachmentlist = "getAttachmentList"
export const fileDelete = "deleteAttachment"
