export class AwardedContracts{
    agency: string;
      awardedContractDate: string;
      awardedContractFromDate: string;
      awardedContractToDate: string;
      awardedContractValue: string;
      companyName: string;
      companytradeLicenseNumber: string;
      contactNumber: string;
      contractDesc: string;
      contractDetails: string;
      contractId: string;
      contractNumber: string;
      contractPeriod: string;
      contractStatus: string;
      contractVendorStatus: string;
      coordinator: string;
      department: string;
      emailId: string;
      mainType: string;
      revisionNumber: string;
      rtaLiaisonOfficer: string;
      section: string;
      siteId: string;
      subType: string;
      tenderId: string;
      tenderName: string;
      tenderNumber: string
}