export class WorkCompletionDtls{
    workId:string;
	boqId:string;
	contractId:string;
	vendorId:string;
	workCompletionDate:string;
	completionPercent:string;
	workDesc:string;
	noOfDays:string;
	itemsDelivered:string;
	claimedAmt:string;
	vatAmt:string;
	totalAmt:string;
	ccRefNo:string;
	workCompletionStatus:string;
	wcVendorStatus:string;
	userId:string;
	createdDate:string;
	modifiedDate:string;
	workCCDocs:Array<any>;
}